### PR TITLE
Added maskColor and maskAlpha to PDFView builder

### PR DESCRIPTION
**Pull request by matteinn**
Now it is possible to change mask color and alpha by calling (for example):

.mask(int color, int alpha)

on the PDFView builder.

As a special case we can hide the prev/next pages previews by calling:

.mask(Color.WHITE, 255)

### CODE REVIEW

**Comment by JoanZapata** [comment]
Thanks @matteinn, will be added in the next release!

**Comment by matteinn** [comment]
ok cool, any idea about the release date?

**Comment by JoanZapata** [comment]
By the end of the week.

**Comment by JoanZapata** [comment]
It's done. `1.0.4` should be available in a few hours on Maven Central.

**Pull request merged**
