### PR TITLE
fix zoom issue

### PR DESCRIPTION
**Pull request by geocf**
fix incorrect start row and column, due to switched middleOfScreenPageX and middleOfScreenPageY calculation

### CODE REVIEW

**Comment by JoanZapata** [comment]
Thanks @geocf

**Comment by cbcnos** [comment]
Thanks so much guys! This lib is awesome

**Comment by emanuelthedude** [comment]
I included the project via Gradle but the fix seems not to be included... Do you publish a new version 1.0.5 or something like that? I tried it on a Nexus 9.

compile 'com.joanzapata.pdfview:android-pdfview:1.0.4@aar'

**Comment by fawaad** [comment]
The build artifact hasn't yet been published to a repo. If you need the fix, a workaround is to pull the code and build it yourself.

**Comment by RichardLindhout** [comment]
Can you please add this to the gradle?

**Pull request merged**
